// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalA2zeL46t7VeITLLcnop2PHsmHcU1EU',
    appId: '1:465142801170:web:4ea5d3ba9cf08d51dd09cb',
    messagingSenderId: '465142801170',
    projectId: 'project-2-the-food-runner',
    authDomain: 'project-2-the-food-runner.firebaseapp.com',
    storageBucket: 'project-2-the-food-runner.firebasestorage.app',
    measurementId: 'G-SW1QWVPPG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7Mz5Aq8-GOO6hlpqfYY2Iqlv1_uyhV4',
    appId: '1:465142801170:android:ca1c9f974a0ed5e8dd09cb',
    messagingSenderId: '465142801170',
    projectId: 'project-2-the-food-runner',
    storageBucket: 'project-2-the-food-runner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-j6HtG0l3rJjYI0tPvzZLK5ctDWJXP4',
    appId: '1:465142801170:ios:63a8f693ca664e0bdd09cb',
    messagingSenderId: '465142801170',
    projectId: 'project-2-the-food-runner',
    storageBucket: 'project-2-the-food-runner.firebasestorage.app',
    iosBundleId: 'com.example.theFoodRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-j6HtG0l3rJjYI0tPvzZLK5ctDWJXP4',
    appId: '1:465142801170:ios:63a8f693ca664e0bdd09cb',
    messagingSenderId: '465142801170',
    projectId: 'project-2-the-food-runner',
    storageBucket: 'project-2-the-food-runner.firebasestorage.app',
    iosBundleId: 'com.example.theFoodRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalA2zeL46t7VeITLLcnop2PHsmHcU1EU',
    appId: '1:465142801170:web:c0600f878ac1ad50dd09cb',
    messagingSenderId: '465142801170',
    projectId: 'project-2-the-food-runner',
    authDomain: 'project-2-the-food-runner.firebaseapp.com',
    storageBucket: 'project-2-the-food-runner.firebasestorage.app',
    measurementId: 'G-D4T50BSE7Q',
  );

}